# Generated by Django 5.0.7 on 2024-12-19 15:36

import api.models.image
import api.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, upload_to=api.models.user.user_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, unique=True)),
                ('is_validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, unique=True)),
                ('subject', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(blank=True, upload_to=api.models.image.image_directory_path)),
                ('caption', models.CharField(blank=True, max_length=256)),
                ('image_number_in_entry', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.entry')),
            ],
        ),
        migrations.CreateModel(
            name='InvitedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('user_who_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='api.entry')),
                ('knowledge_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='api.knowledgearea')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
                ('explanation', models.CharField(blank=True, max_length=256)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=16)),
                ('grammatical_category', models.CharField(blank=True, choices=[('substantivo', 'Substantive'), ('verbo', 'Verb'), ('adjetivo', 'Adjective'), ('numeral', 'Numeral')], max_length=16)),
                ('is_main_term', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Syllable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=16)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.term')),
            ],
        ),
    ]
