# Generated by Django 5.0.7 on 2025-02-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearea',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
    ]
