# Generated by Django 5.0.7 on 2024-10-22 12:48

import api.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.ImageField(upload_to=api.models.image.image_directory_path),
        ),
    ]
