# Generated by Django 5.0.7 on 2024-10-19 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.entry'),
        ),
    ]
