# Generated by Django 5.0.7 on 2024-10-20 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_term_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='knowledge_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='api.knowledgearea'),
        ),
        migrations.AlterField(
            model_name='image',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.entry'),
        ),
        migrations.AlterField(
            model_name='question',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.entry'),
        ),
    ]
