# Generated by Django 5.0.7 on 2024-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_entry_syllable_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAreaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='term',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=16),
        ),
        migrations.AlterField(
            model_name='term',
            name='grammatical_category',
            field=models.CharField(blank=True, choices=[('substantivo', 'Substantive'), ('verbo', 'Verb'), ('adjetivo', 'Adjective'), ('numeral', 'Numeral')], max_length=16),
        ),
    ]
