# Generated by Django 5.0.7 on 2024-10-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_definition_knowledge_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='knowledge_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='api.knowledgearea'),
        ),
    ]
