# Generated by Django 5.0.7 on 2024-10-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_knowledgeareamanager_alter_term_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeAreaManager',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='order',
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='syllable',
            name='order',
        ),
        migrations.RemoveField(
            model_name='term',
            name='order',
        ),
    ]
