# Generated by Django 5.0.7 on 2024-10-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_definition_knowledge_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='api.entry'),
        ),
    ]
